---
title: "Antecedents to and Effects of Advanced Coursework"
format: gfm
---

## Description

This project investigates the factors that lead to student involvement in advanced educational programs and the outcomes associated with such participation. The primary objectives are to identify the demographic, socioeconomic, and institutional variables that serve as precursors to enrollment in these programs and to analyze the impact that participation has on students’ academic and career trajectories. By conducting a comprehensive analysis of student data from middle school through high school graduation, this project seeks to provide actionable insights that can inform district policy and program development.

## Project Organization

- `/code` Scripts with prefixes (e.g., `01_import-data.py`, `02_clean-data.py`) and functions in `/code/src`.
- `/data` Simulated and real data, the latter not pushed.
- `/figures` PNG images and plots.
- `/output` Output from model runs, not pushed.
- `/private` A catch-all folder for miscellaneous files, not pushed.
- `/.venv` Hidden project library, not pushed.
- `.gitignore` Hidden Git instructions file.
- `.python-version` Hidden Python version file.
- `pyproject.toml` Project environment configuration file.
- `uv.lock` Project environment lock file.

## Project Environment

After cloning this repository, go to the project's terminal in Positron and run `uv run` to create the `/.venv` project library and install the specified Python and library versions.

For more details on using Python, Positron, GitHub, Quarto, etc. see the recommended [Data Stack](https://github.com/marcdotson/data-stack).

